---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cert-manager-webhook-he.fullname" . }}:flowcontrol
  labels:
    app: {{ include "cert-manager-webhook-he.name" . }}
    chart: {{ include "cert-manager-webhook-he.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
  - apiGroups:
      - "flowcontrol.apiserver.k8s.io"
    resources:
      - 'flowschemas'
      - 'prioritylevelconfigurations'
    verbs:
      - 'list'
      - 'watch'
      - 'get'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cert-manager-webhook-he.fullname" . }}:flowcontrol
  labels:
    app: {{ include "cert-manager-webhook-he.name" . }}
    chart: {{ include "cert-manager-webhook-he.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cert-manager-webhook-he.fullname" . }}:flowcontrol
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ include "cert-manager-webhook-he.fullname" . }}
    namespace: {{ .Release.Namespace }}
---
{{- if .Values.auth.useSecrets }}
{{- if .Values.rbac.secretNamespaces }}
{{- range $namespace := .Values.rbac.secretNamespaces }}
{{ include "cert-manager-webhook-he.secretReaderRole" (list $ "role" $namespace) }}
{{- end }}
{{- else }}
{{ include "cert-manager-webhook-he.secretReaderRole" (list $ "clusterrole" "") }}
{{- end }}
{{- end }}